### ISSUE TITLE
Không cho vào khi nhập đúng sau khi nhập sai

### ISSUE THREAD

**Issue by phamtrongthang123** [lamnhh/sql-1#3]
Khi cố tình nhập sai cỡ 10-11 lần thì lần kế dù nhập đúng cũng không cho vào.  Và nó làm lag server một chút. Ở cả add staff và add department đều thế.
[xem](https://youtu.be/J6OpdbXBLAo)

**Comment by lamnhh** [comment]
Fixed in PR #5
