### ISSUE TITLE
File xuất ra csv bị lỗi gì đó, chắc vấn đề unicode 

### ISSUE THREAD

**Issue by phamtrongthang123** [lamnhh/sql-1#4]
Xuất ra file csv nội dung đọc không ra, kí tự unicode bị sai giống như từ utf 8 mà in ra thuần char vậy. 
![image](https://user-images.githubusercontent.com/17172232/55736833-4e5a4b00-5a4e-11e9-8513-83164b2ebc9b.png)

**Comment by lamnhh** [comment]
Probably due to utf-8 encoding. I tried saving the csv file (from Notepad) with Unicode encoding and it works fine.

Anyway, this is the plugin's fault, not mine :v

**Comment by phamtrongthang123** [comment]
Could be, then fix the plugin!
